// Generated by CoffeeScript 1.7.1
(function() {
  var extract, utils;

  utils = require('./utils');


  /*
  Extract features from a JSON object
   */

  extract = function(event, facts, prefix) {
    var key, value;
    if (facts == null) {
      facts = [];
    }
    if (prefix == null) {
      prefix = "";
    }

    /*
    This was supposed to be a built-in support for a "date" attribute
    TODO but it is a bit awkward: we should rather use the schema for that.
    let's disable it for now.
     */
    for (key in event) {
      value = event[key];
      key = prefix + key;
      if (utils.isString(value)) {
        facts.push(['String', key, value]);
      } else if (utils.isArray(value)) {
        facts.push(['Array', key, value]);
      } else if (utils.isNumber(value)) {
        facts.push(['Number', key, value]);
      } else if (utils.isBoolean(value)) {
        facts.push(['Boolean', key, value]);
      } else {
        extract(value, facts, key + ".");
      }
    }
    return facts;
  };

  module.exports = extract;

}).call(this);
