// Generated by CoffeeScript 1.6.3
(function() {
  var NEGATIVE, NEUTRAL, POSITIVE, debug, enrich, ngramize, thesaurus,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  thesaurus = require('thesaurus');

  debug = function() {};

  enrich = function(words) {
    var anotherWord, moreWords, word, _i, _j, _len, _len1, _ref;
    moreWords = [];
    for (_i = 0, _len = words.length; _i < _len; _i++) {
      word = words[_i];
      _ref = thesaurus.find(word);
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        anotherWord = _ref[_j];
        if (__indexOf.call(moreWords, anotherWord) < 0) {
          moreWords.push(anotherWord);
        }
      }
    }
    return moreWords;
  };

  POSITIVE = exports.POSITIVE = +1;

  NEGATIVE = exports.NEGATIVE = -1;

  NEUTRAL = exports.NEUTRAL = 0;

  ngramize = function(words, n) {
    var gram, grams, i, k, subgrams, v, w, _i, _j, _len, _ref;
    if (!Array.isArray(words)) {
      words = words.split(' ');
    }
    grams = {};
    if (n < 2) {
      for (_i = 0, _len = words.length; _i < _len; _i++) {
        w = words[_i];
        grams["" + w] = Array.isArray(w) ? w : [w];
      }
      return grams;
    }
    for (i = _j = 0, _ref = words.length; 0 <= _ref ? _j < _ref : _j > _ref; i = 0 <= _ref ? ++_j : --_j) {
      gram = words.slice(i, i + n);
      subgrams = ngramize(gram, n - 1);
      for (k in subgrams) {
        v = subgrams[k];
        grams[k] = v;
      }
      if (i > words.length - n) {
        break;
      }
      grams["" + gram] = gram;
    }
    return grams;
  };

  exports.Engine = (function() {
    function Engine(opts) {
      var _ref, _ref1, _ref2;
      if (opts == null) {
        opts = {};
      }
      this.stringSize = (_ref = opts.stringSize) != null ? _ref : [0, 30];
      this.ngramsSize = (_ref1 = opts.ngramsSize) != null ? _ref1 : 2;
      this.debug = (_ref2 = opts.debug) != null ? _ref2 : false;
      debug = debug ? console.log : function() {};
      this.profiles = {};
    }

    Engine.prototype.pushEvent = function(event) {
      var changed, facet, profile, synonym, _, _i, _len, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6;
      if (event.signal === NEUTRAL) {
        debug("signal is neutral, ignoring");
        return;
      }
      if (this.profiles[event.profile] == null) {
        debug("creating profile for " + event.profile);
        this.profiles[event.profile] = {};
      }
      profile = this.profiles[event.profile];
      debug("updating profile " + event.profile + "..");
      changed = {
        content: 0,
        synonyms: 0
      };
      _ref = ngramize(event.content, this.ngramsSize);
      for (facet in _ref) {
        _ = _ref[facet];
        if (!((this.stringSize[0] < (_ref1 = facet.length) && _ref1 < this.stringSize[1]))) {
          continue;
        }
        profile[facet] = event.signal + ((_ref2 = profile[facet]) != null ? _ref2 : 0);
        changed.content++;
      }
      _ref3 = enrich(event.content.split(' '));
      for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
        synonym = _ref3[_i];
        _ref4 = ngramize(synonym, 3);
        for (facet in _ref4) {
          _ = _ref4[facet];
          if (!((this.stringSize[0] < (_ref5 = facet.length) && _ref5 < this.stringSize[1]))) {
            continue;
          }
          profile[facet] = event.signal + ((_ref6 = profile[facet]) != null ? _ref6 : 0);
          changed.synonyms++;
        }
      }
      return debug("" + (event.signal > 0 ? 'reinforced' : 'weakened') + " " + (JSON.stringify(changed)) + " facets");
    };

    Engine.prototype.prune = function(min, max) {
      var facet, facets, profile, _, _ref, _results;
      _ref = this.profiles;
      _results = [];
      for (profile in _ref) {
        facets = _ref[profile];
        _results.push((function() {
          var _ref1, _results1;
          _results1 = [];
          for (facet in facets) {
            _ = facets[facet];
            facets[facet] = facets[facet] - 1;
            if ((min < (_ref1 = facets[facet]) && _ref1 < max)) {
              _results1.push(delete facets[facet]);
            } else {
              _results1.push(void 0);
            }
          }
          return _results1;
        })());
      }
      return _results;
    };

    Engine.prototype.matchOne = function(id, content) {};

    Engine.prototype.matchAll = function(content, N) {};

    return Engine;

  })();

}).call(this);
