// Generated by CoffeeScript 1.4.0
(function() {
  var extractLinks, extractTitle, fetchTitle;

  exports.extractLinks = extractLinks = function(txt) {
    var results, urlRegex;
    urlRegex = /(https?:\/\/[^\s]+)/g;
    results = [];
    ("" + txt).replace(urlRegex, function(url) {
      return results.push(url);
    });
    return results;
  };

  exports.extractTitle = extractTitle = function(html) {
    var pattern, results, title, _ref;
    pattern = /<title>([^<]*)<\/title>/;
    results = html.match(pattern);
    title = results != null ? (_ref = results[1]) != null ? _ref : "" : "";
    return title.replace('&amp;', '&').replace('&nbsp;', ' ');
  };

  exports.fetchTitle = fetchTitle = function(url, onComplete) {
    var request;
    request = function() {};
    try {
      request = require('request');
    } catch (e) {
      throw new Error("Youneed to install node-request before using fetchTitle");
    }
    console.log("downloading " + url);
    return request(url, function(error, response, body) {
      if (error) {
        console.log("couldn't download " + url);
      }
      return onComplete(extractTitle(body != null ? body : ''));
    });
  };

}).call(this);
